### ISSUE TITLE
Please consider reorganize the `plone.volto` requirement.

### ISSUE THREAD

**Issue by me-kell** [plone/Plone#25]
https://github.com/plone/Plone/blob/fc31ec477621766fbf42e7595bdd6321cee18b9d/setup.cfg#L38

Please consider reorganize the `plone.volto` requirement.

AFAICS for backend only (i.e. Classic UI) installations it is not really necessary.

**Comment by davisagli** [comment]
Installing the `Plone` egg gives you the required Plone packages as well as some additional packages supported by the core developers that don't do anything unless you install them. plone.volto is meant to be in that group of packages -- if you're seeing it change something in a Classic UI site even though it hasn't been installed, please report the specific issue in the plone.volto repository. If you want a more minimal set of packages, install Products.CMFPlone instead of Plone.

**Comment by me-kell** [comment]
@davisagli Thanks for the info.

It should be mentioned that installing `Products.CMFPlone` alone won't give you the following packages: `plone.app.caching`, `plone.app.iterate`, `plone.app.upgrade`, `plone.restapi`, `plone.volto`, `Products.CMFPlacefulWorkflow`.

**Comment by gyst** [comment]
Note that this causes breakage if you use `collective.recipe.plonesite` because Products.CMFPlone will create a Volto site if the Volto eggs are detected.
https://github.com/plone/Products.CMFPlone/blob/8e7283a44b2209f40b17f7d0ad338b06bea32ef1/Products/CMFPlone/browser/admin.py#L166
